### ISSUE TITLE
缺少头文件

### ISSUE THREAD

**Issue by songjiasunhao** [1989Ryan/Semantic_SLAM#2]
你好，我在编译过程中出现错误
map_generator/mp.h: 没有那个文件或目录
compilation terminated.

**Comment by poetgeorge** [comment]
ros版本是kinetic吗

**Comment by lihao815** [comment]
遇到了同样的问题，请问你解决了吗？

**Comment by nixwang** [comment]
这个需要下载ros map generator包一起编译[https://github.com/karvozavr/ROS-Map-Generator](url)

**Comment by 1989Ryan** [comment]
hi, 感谢参考本项目,缺少头文件应该是因为编译的顺序问题,由于我在编译的时候先编译了map_generator,后编译了剩余部分,所以才会有问题.
