### ISSUE TITLE
重复文件

### ISSUE THREAD

**Issue by longzhiyu-code** [1989Ryan/Semantic_SLAM#3]
你好，我对这个语义slam的工作很感兴趣，在Semantic_SLAM/Third_Part/PSPNet_Keras_tensorflow的路径下Semantic_Information_Publisher_C.py与Semantic_Information_Publisher.py的内容是相同的，是不是误传了？

**Comment by 1989Ryan** [comment]
你好,谢谢,确实是duplicated file.
